name: hello-world
permissions:
  id-token: write # This is required for requesting the JW
  contents: read  # This is required for checkout
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.2.2
        with:
          url: ${{ vars.CONJUR_URL }}
          account: ${{ vars.CONJUR_ACCOUNT }}
          authn_id: ${{ vars.CONJUR_AUTHN_ID }}
          secrets: |
            data/vault/SM-AWS-SecretHub/aws-dummy-account/username|SECRET1
            data/vault/SM-AWS-SecretHub/aws-dummy-account/password|SECRET2
            
      - name: Echo USERNAME
        run: echo $SECRET1 | sed 's/./& /g'
        
      - name: Echo PASSWORD
        run: echo $SECRET2 | sed 's/./& /g'
